### ISSUE TITLE
shipa.io no way to contact you

### ISSUE THREAD

**Issue by modigithub** [shipa-corp/dotnet-sample#2]
hi I want to use your shipa.io software to deploy my microservice project. But i have some questions and no idea how to contact you. If i click on your website contact us i got an empty page. 
![image](https://user-images.githubusercontent.com/108171635/197461521-327c0b4b-5bd9-4ee7-b1a9-9a27b5962203.png)

**Comment by vivek** [comment]
Hi @modigithub, Sorry about the `Contact Us page` not reachable, we will look in to it. 

You can reach to us via our [community slack channel](http://url9210.shipa.io/ls/click?upn=Qwbu9oAywQ36xHJw19FZABWvdwNWDoDrsYA6k-2FrU7GOLvqR4Jbuvf-2FtBz65jnonC7ZJjNRBKrRmEVlb5Vnpw2EfjEYZgi4AEcdfZYAmEB4Vj09nGowwCPm0-2F2kIn5sfB8lnR_qSdTG-2F-2BgpwCzv8q1AgYW4-2FCipmypevw7ht7H6ZSaDBxZ32HMlitS688uIYy3QX8XAUz7L8AJkIgjbYQKrYqsku5PNHgk4R2vylqdip3oWvfnrHhhB1plQmVhlkZ-2FrjCYtdxrvdgvsrriynkdK7UNJ6ss6Wf9FXHrojAfvbYZmXHCrlIKlZsmZ6E2gFaBrA11vczciuS4h9exlWHL9ImsfwLY6q0rDKFGpB-2FkT5kQkiZx-2Ft4giZhHxB5VFISJYJ8WBjkVE-2FRFAMWDU-2BCwEDVMnzu0oifrohL8RuK1DTJBSJHeS-2B-2BkLzUdXS75iw1eU5uTXQqcg-2FvisGFvp1CS3TRXexREV-2BHBYgO7qvGrlkfxFng-3D) or via email support@shipa.io.
